# Generated by Django 6.0 on 2026-01-06 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0003_alter_discussioncomment_id_alter_discussionpost_id'),
        ('users', '0010_remove_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussioncomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_comments', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='discussionpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_posts', to='users.profile'),
        ),
    ]
